"""empty message

Revision ID: 6b782217ecf7
Revises: ffdc0a98111c
Create Date: 2021-08-24 18:23:47.787704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b782217ecf7'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilePhotoUrl', sa.String(length=500), nullable=False))
    op.add_column('users', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    op.drop_column('users', 'profilePhotoUrl')
    # ### end Alembic commands ###
